### PR TITLE
User submissions

### PR DESCRIPTION
**Pull request by Ymihere03**
My first attempt at allowing the logged in user to make an edit to the game that they own.

An update button displays to let the user update only the game that belongs to them, but still working on issues with the actual data update. The game gets erased from the data store instead of being updated after the update button is clicked.

### CODE REVIEW

**Comment by Ymihere03** [comment]
I didn't see any data stored that indicates what the current week is. It might be worthwhile to add in a current week marker so that users are not able to update future weeks.

**Comment by redmanatee** [comment]
Except in some rare cases (usually at least once a season) we have users who have to play their next week's game early.

**Comment by Ymihere03** [comment]
Ah, ok. I forgot about that.

**Comment by redmanatee** [comment]
I will get to these PRs this week - apologies on the delays.  Between conferences, craziness at the day job, and family stuff I haven't had time.

**Pull request merged**
